-- menu_items table seeds --
-- FOR THE TABLE --
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CEVICHE', 'created by chef rob feenie. ocean wise™ lois lake steelhead, sustainably harvested prawns, red onions, thai basil, mint, cilantro, nuoc cham', 'https://i.pinimg.com/736x/71/c9/40/71c9407b8a4ceecaea81e0b4a86d08a3--cactus-toronto.jpg', 1825, NULL, 7, 1);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('SZECHUAN LETTUCE WRAPS', 'sweet and spicy szechuan chicken or tofu, peanuts, wontons, korean chili sauce, spicy yogurt', 'http://4.bp.blogspot.com/-6AzQUlm5JnY/VfsWCpM-UBI/AAAAAAAAOUU/DfSz_SnxDsI/s1600/IMG_5784.JPG', 1875, NULL, 6, 1);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('TUNA STACK', 'created by chef rob feenie. ocean wise™ ahi, citrus tamari vinaigrette, nori, sesame, avocado, micro cilantro, wonton chips', 'https://noshandnibble.blog/content/images/2018/07/cactus-club-park-royal-tuna-stack.jpg', 1875, NULL, 4, 1);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CALAMARI', 'peppers, jalapeños, dill, tzatziki, chipotle aioli', 'https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/38614630_10160869515085171_4571775112138719232_n.jpg?_nc_cat=108&_nc_oc=AQnMNHzgWPdmhAtXZRP0dSIsDhsByeBVAMoJoMSRMyr98wL_IZQcrn0iBbWBvLRO0YY&_nc_ht=scontent-sea1-1.xx&oh=ebef4bf030f0262db6462fab713295b8&oe=5E2E8DB4', 1600, NULL, 6, 1);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CHIMICHURRI GUACAMOLE', 'feta, baby gem tomatoes, pumpkin seeds, chimichurri, cilantro, corn tortilla chips', 'https://pbs.twimg.com/media/DiqF7BaWsAY1PIB.jpg', 1375, NULL, 5, 1);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('EDAMAME', 'steamed soybeans, sea salt', 'https://s3-media2.fl.yelpcdn.com/bphoto/ustrICnZ2zYPWINgC9cOmg/o.jpg', 900, NULL, 6, 1);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CRIPSY YAM FRIES', 'garlic aioli', 'https://sunnyyq.files.wordpress.com/2012/08/12-08-10-crispy-yam-fries-cactus-club-cafe.jpg', 975, NULL, 4, 1);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('TRUFFLE FRIES', 'truffle, herbs, grana padano, garlic aioli', 'https://s3-media1.fl.yelpcdn.com/bphoto/OHmkAdPAEn-sCZJDiE72xg/o.jpg', 1025, NULL, 4, 1);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CHICKEN WINGS', 'louisiana hot, celery, creamy parmesan dip', 'https://s3-media4.fl.yelpcdn.com/bphoto/e0vmA3k5DyMXmKN6ggFj5w/o.jpg', 1575, NULL, 7, 1);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('SPICY CHICKEN', 'sweet chili glaze, crispy wontons, green onions', 'https://static.wixstatic.com/media/9b3c70_353336ccea98474da23e6e33e0d50f19~mv2.jpg/v1/fill/w_308,h_228,al_c,q_80,usm_1.20_1.00_0.01/9b3c70_353336ccea98474da23e6e33e0d50f19~mv2.webp', 1525, NULL, 7, 1);
-- GREENS -- ST to any salad grilled chicken breast, grilled salmon, sauteed prawns
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('RAINCOAST GREENS', 'fresh greens, grilled chicken breast, avocado, tomatoes, feta, spicy pecans, cucumber, egg, lemon-thyme vinaigrette', 'https://media-cdn.tripadvisor.com/media/photo-s/05/75/ca/4f/green-salad.jpg', 1975, NULL, 11, 2);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('ROCKET SALAD', 'created by chef rob feenie. parmesan crusted chicken breast, arugula, baby gem tomatoes, red onion, lemon caper dressing', 'https://pbs.twimg.com/media/DrRV4opW4AAe98n.jpg', 1975, NULL, 13, 2);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('KALE + GRILLED CHICKEN SALAD', 'kale, fresh greens, romaine, dijon-lemon vinaigrette, pickled red onions, parmesan crumble', 'https://pbs.twimg.com/media/DZAU7O7VwAAPJDY.jpg', 1875, NULL, 11, 2);
-- BOWLS --
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('MODERN BOWL', 'tabbouleh, pineapple salsa, roasted cauliflower and broccoli, tomatoes, cucumber, fresh greens, jasmine rice, miso carrot ginger sauce', 'https://media-cdn.tripadvisor.com/media/photo-s/10/6c/d0/9f/the-modern-bowl.jpg', 2050, NULL, 12, 3); -- ST griled chicken, grilled avacado,, glazed salmon, soy grilled tofu
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, special, course_id) VALUES ('TUNA POKE BOWL', 'sesame ginger ocean wise™ ahi, jasmine rice, mango, cucumber, avocado, edamame, radish, crispy tempura', 'https://s3-media2.fl.yelpcdn.com/bphoto/mu6i5rAzJAF-5Sl7NyHogQ/o.jpg', 2050, NULL, 14, TRUE, 3);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CRIPSY TOFU BOWL', '100% plant-based. soy chili tofu, jasmine rice, mango, cucumber, avocado, edamame, radish', 'https://i1.wp.com/fullofplants.com/wp-content/uploads/2017/12/sweet-chili-tofu-bowls-with-avocado-and-rice-thumb-5.jpg?fit=1351%2C1351&ssl=1', 1925, NULL, 11, 3);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('TERIYAKI CHICKEN RICE BOWL', 'bell peppers, broccoli, braised red cabbage, bean sprouts, spicy yogurt', 'https://s3-media2.fl.yelpcdn.com/bphoto/9jC6afTUGhKXn1vpXoxIlw/o.jpg', 1975, NULL, 13, 3);
-- CASUAL --
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('BAJA FISH TACOS', 'beer battered ocean wise™ cod, shredded cabbage, chipotle aioli, fire roasted tomato salsa, pickled radish, onions and jalapeños, sea salted fries.', 'https://media-cdn.tripadvisor.com/media/photo-s/10/52/6f/d3/fish-tacos.jpg', 1875, NULL, 8, 4); -- ST guac option
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('MINI CRISPY CHICKEN SANDWICHES', 'spicy panko-crusted chicken, swiss cheese, sambal mayo, lettuce, tomato, pickle, onion', 'https://fafifotography.files.wordpress.com/2018/05/img_20180506_192712_285.jpg', 1550, NULL, 11, 4);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('MINI BURGERS', 'certified angus beef®, cheddar, bacon, lettuce, tomato, red pepper relish, dijon mayonnaise', 'https://secureservercdn.net/184.168.47.225/c9f.6a7.myftpupload.com/wp-content/uploads/2015/01/IMG_1608-copy.jpg', 1550, NULL, 10, 4);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, special, course_id) VALUES ('ROBS FLATBREAD', 'caramelized onions, grape tomatoes, feta, goat cheese, basil pesto, arugula, balsamic glaze', 'http://1.bp.blogspot.com/-kpo0Q8KHJVc/ThOrscg6KDI/AAAAAAAAAGk/csXPUaOBypk/s1600/DSC_0796.jpg', 1625, NULL, 6, TRUE, 4);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CHICKEN TENDERS', 'panko-breaded chicken, sea salted fries, honey mustard dip', 'https://s3-media1.fl.yelpcdn.com/bphoto/46fg6AEESI3PpXEABILzfA/o.jpg', 1625, NULL, 4, 4);
-- SEAFOOD --
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('GRILLED DIJON SALMON', 'ocean wise™ lois lake steelhead, buttered mashed potatoes, roasted asparagus, soy-dijon butter sauce, cilantro', 'https://www.cmeexpo.ca/wp-content/uploads/2019/04/SalmonFresca.jpg', 2575, NULL, 14, 5);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('THAI RED CURRY + PRAWNS', 'sustainably harvested prawns, peppers, green beans, baby corn, bamboo shoots, jasmine rice, bean sprouts, wontons, cilantro', 'https://img.taste.com.au/muoUe866/taste/2016/11/prawn-potato-curry-75818-1.jpeg', 2225, NULL, 14, 5);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('SABLEFISH', 'shiitake mushrooms, asparagus, peking duck broth, yukon gold potatoes', 'https://images.thestar.com/IuGCplwVLGNVSWE1Bft5Zo-9WyE=/1200x858/smart/filters:cb(2700061000)/https://www.thestar.com/content/dam/thestar/life/food_wine/2015/11/04/restaurant-news-cactus-club-cafe-finally-opens-splendido-to-close/cactus-club-toronto.jpg', 3975, NULL, 12, 5);
-- PASTA --
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('BUTTERNUT SQUASH RAVIOLI WITH PRAWNS', 'chef rob feenie’s signature butternut squash and mascarpone ravioli, truffle butter, sautéed jumbo prawns, pine nuts, crispy sage', 'https://media-cdn.tripadvisor.com/media/photo-s/06/e1/96/f4/cactus-club-cafe.jpg', 2825, NULL, 14, 6);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('SPAGHETTINI + KOBE STYLE MEATBALLS', 'roasted tomato sauce, truffle mushroom cream, fresh ricotta cheese', 'https://s3-media3.fl.yelpcdn.com/bphoto/x2XCaZPRXlwK887MNlnjLA/o.jpg', 2775, NULL, 14, 6);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('PRAWN SPAGHETTINI', 'slow-roasted tomato sauce, chilies, fresh herbs, crostini', 'https://s3-media1.fl.yelpcdn.com/bphoto/orZyOL8fX6KQelxU12qjsg/o.jpg', 2100, NULL, 14, 6);
-- CHICKEN --
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('BLACKENED CREOLE CHICKEN', 'creole butter, cajun spices, buttered mashed potatoes, roasted asparagus', 'https://s3-media1.fl.yelpcdn.com/bphoto/zIVWUkUBvL1slnKRqYN2vQ/o.jpg', 2600, NULL, 15, 7);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('HUNTER CHICKEN', 'shiitake, portobello, button and crimini mushroom demi-glace, buttered mashed potatoes, green beans', 'https://i.pinimg.com/originals/6b/20/f6/6b20f6f11705d8931eda2fa2ae24819c.jpg', 2725, NULL, 14, 7);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('THAI RED CURRY + CHICKEN', 'peppers, green beans, baby corn, bamboo shoots, jasmine rice, bean sprouts, wontons, cilantro', 'https://www.cactusclubcafe.com/wp-content/uploads/2017/10/thai-red-curry-lingcod-620x388.jpg', 2100, NULL, 14, 7);
-- BURGERS + SANDWICHES -- ST cheddar cheese, mushrooms bacon
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('THE FEENIE BURGER', 'smashed certified angus beef®, sautéed mushrooms, aged cheddar, smoked bacon, red relish, mayonnaise, ketchup, mustard', 'http://tideandthyme.com/wp-content/uploads/2013/02/mushroomonionswissburger.jpg', 1975, NULL, 10, 8);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CHEDDAR BACON BURGER', 'smashed certified angus beef®, aged cheddar, smoked bacon, red relish, mayonnaise, ketchup, mustard', 'https://www.cactusclubcafe.com/wp-content/uploads/2016/05/050616_FortMcMurray_Blog_620px_400px_notext_web.jpg', 1850, NULL, 11, 8);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('BBQ DUCK CLUBHOUSE', 'created by chef rob feenie. peking duck, roasted chicken, prosciutto di modena, pecan fruit bread', 'https://pbs.twimg.com/media/D0iAH9IWwAEyA3n.jpg', 1975, NULL, 8, 8);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('GARDENBURGER', 'aged cheddar, red relish, mayonnaise, ketchup, mustard, multigrain bun', 'https://www.blogto.com/listings/restaurants/upload/2014/09/20140902-localpubliceatery590-10.jpg', 1750, NULL, 6, 8);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CAJUN CHICKEN SANDWICH', 'aged cheddar, lettuce, tomato', 'https://i.pinimg.com/originals/b0/f3/ba/b0f3ba25daf8d625b0aee242f17fee82.jpg', 1700, NULL, 8, 8);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('ROBS CRISPY CHICKEN SANDWICH', 'spicy panko-crusted chicken, swiss cheese, sambal mayo, lettuce, tomato, pickle and onion', 'https://pbs.twimg.com/media/Dv2Bi--X0AAsIZ4.jpg', 1775, NULL, 8, 8);
-- DESSERTS --
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('APPLE GALETTE', 'flaky puff pastry, caramelized apples, tahitian vanilla ice cream, caramel sauce', 'https://www.cactusclubcafe.com/wp-content/uploads/2010/06/Picture-0251.jpg', 1000, NULL, 3, 9);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CHOCOLATE PEANUT BUTTER CRUNCH BAR', 'tahitian vanilla ice cream, caramel sauce, crunchy chocolate pearls', 'https://i.pinimg.com/originals/b8/b5/fb/b8b5fb59de059067ae56f016be104e17.jpg', 1000, NULL, 1, 9);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CARAMEL CHOCOLATE MOUSSE', 'warm caramel foam, crunchy sponge toffee, velvety chocolate mousse', 'https://i.pinimg.com/originals/17/84/46/178446f3446fea20d1eae0e5365f16d3.jpg', 350, NULL, 5, 9); -- ST single, double, triple
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('WHITE CHOCOLATE CHEESECAKE', 'chocolate cookie crust, raspberry compote, hand whipped cream', 'https://i.pinimg.com/originals/b0/7e/b8/b07eb86cbcb152375dfec4357e1aaed8.jpg', 1000, NULL, 3, 9);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('KEY LIME PIE', 'freshly squeezed key limes, graham cracker crust, hand whipped cream', 'https://gastrofork.ca/wp-content/uploads/2017/04/cactusclubdesserts-3447-1280x860.jpg', 1000, NULL, 3, 9);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CHOCOLATE LAVA CAKE', 'molten dark chocolate cake, tahitian vanilla ice cream', 'http://foodology.ca/wp-content/uploads/2017/04/cactus-club-dessert-lunch-11-620x413.jpg', 1000, NULL, 3, 9);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('PUMPKIN CHEESECAKE', 'warm spices, toasted walnuts, caramel sauce, fresh whipped cream. available for a limited time', 'https://pbs.twimg.com/media/DnaXPauXsAAKuom.jpg', 950, NULL, 3, 9);
-- DRINKS --
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('COKE', NULL, NULL, 200, null, 1, 10);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('ICE TEA', NULL, NULL, 200, null, 1, 10);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('SPRITE', NULL, NULL, 200, null, 1, 10);
-- SIDES --
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('GRILLED CHICKEN BREAST', NULL, NULL, 500, null, 5, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('GRILLED SALMON', NULL, NULL, 800, null, 5, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('SAUTEED PRAWNS', NULL, NULL, 800, null, 5, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('GRILLED AVOCADO', NULL, NULL, 300, null, 3, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('SOY GRILLED TOFU', NULL, NULL, 300, null, 3, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('GUACAMOLE', NULL, NULL, 200, null, 1, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('CHEDDER CHEESE', NULL, NULL, 100, null, 1, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('MUSHROOMS', NULL, NULL, 200, null, 3, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('BACON', NULL, NULL, 150, null, 2, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('FRIES', NULL, NULL, 200, null, 2, 11);
INSERT INTO menu_items (title, description, image_url, price, calories, prep_time, course_id) VALUES ('GREEN SALAD', NULL, NULL, 150, null, 2, 11);


